#define Y_NAMED_COLORS 190
#define Y_BLACK              upsylon::Graphic::rgb(0x00,0x00,0x00)
#define Y_BLACK_INDEX              0
#define Y_GREEN_DARK         upsylon::Graphic::rgb(0x00,0x64,0x00)
#define Y_GREEN_DARK_INDEX         1
#define Y_IVORY_BLACK        upsylon::Graphic::rgb(0x29,0x24,0x21)
#define Y_IVORY_BLACK_INDEX        2
#define Y_NAVY               upsylon::Graphic::rgb(0x00,0x00,0x80)
#define Y_NAVY_INDEX               3
#define Y_VAN_DYKE_BROWN     upsylon::Graphic::rgb(0x5e,0x26,0x05)
#define Y_VAN_DYKE_BROWN_INDEX     4
#define Y_INDIGO             upsylon::Graphic::rgb(0x08,0x2e,0x54)
#define Y_INDIGO_INDEX             5
#define Y_SEPIA              upsylon::Graphic::rgb(0x5e,0x26,0x12)
#define Y_SEPIA_INDEX              6
#define Y_MIDNIGHT_BLUE      upsylon::Graphic::rgb(0x19,0x19,0x70)
#define Y_MIDNIGHT_BLUE_INDEX      7
#define Y_TERRE_VERTE        upsylon::Graphic::rgb(0x38,0x5e,0x0f)
#define Y_TERRE_VERTE_INDEX        8
#define Y_ULTRAMARINE        upsylon::Graphic::rgb(0x12,0x0a,0x8f)
#define Y_ULTRAMARINE_INDEX        9
#define Y_LAMP_BLACK         upsylon::Graphic::rgb(0x2e,0x47,0x3b)
#define Y_LAMP_BLACK_INDEX         10
#define Y_OLIVE              upsylon::Graphic::rgb(0x3b,0x5e,0x2b)
#define Y_OLIVE_INDEX              11
#define Y_SAP_GREEN          upsylon::Graphic::rgb(0x30,0x80,0x14)
#define Y_SAP_GREEN_INDEX          12
#define Y_DEEP_OCHRE         upsylon::Graphic::rgb(0x73,0x3d,0x1a)
#define Y_DEEP_OCHRE_INDEX         13
#define Y_BLUE_MEDIUM        upsylon::Graphic::rgb(0x00,0x00,0xcd)
#define Y_BLUE_MEDIUM_INDEX        14
#define Y_SLATE_GREY_DARK    upsylon::Graphic::rgb(0x2f,0x4f,0x4f)
#define Y_SLATE_GREY_DARK_INDEX    15
#define Y_BURNT_SIENNA       upsylon::Graphic::rgb(0x8a,0x36,0x0f)
#define Y_BURNT_SIENNA_INDEX       16
#define Y_FOREST_GREEN       upsylon::Graphic::rgb(0x22,0x8b,0x22)
#define Y_FOREST_GREEN_INDEX       17
#define Y_RAW_UMBER          upsylon::Graphic::rgb(0x73,0x4a,0x12)
#define Y_RAW_UMBER_INDEX          18
#define Y_BROWN              upsylon::Graphic::rgb(0x80,0x2a,0x2a)
#define Y_BROWN_INDEX              19
#define Y_BURNT_UMBER        upsylon::Graphic::rgb(0x8a,0x33,0x24)
#define Y_BURNT_UMBER_INDEX        20
#define Y_SADDLE_BROWN       upsylon::Graphic::rgb(0x8b,0x45,0x13)
#define Y_SADDLE_BROWN_INDEX       21
#define Y_INDIAN_RED         upsylon::Graphic::rgb(0xb0,0x17,0x1f)
#define Y_INDIAN_RED_INDEX         22
#define Y_BROWN_OCHRE        upsylon::Graphic::rgb(0x87,0x42,0x1f)
#define Y_BROWN_OCHRE_INDEX        23
#define Y_ULTRAMARINE_VIOLET upsylon::Graphic::rgb(0x5c,0x24,0x6e)
#define Y_ULTRAMARINE_VIOLET_INDEX 24
#define Y_MARS_ORANGE        upsylon::Graphic::rgb(0x96,0x45,0x14)
#define Y_MARS_ORANGE_INDEX        25
#define Y_OLIVE_GREEN_DARK   upsylon::Graphic::rgb(0x55,0x6b,0x2f)
#define Y_OLIVE_GREEN_DARK_INDEX   26
#define Y_FIREBRICK          upsylon::Graphic::rgb(0xb2,0x22,0x22)
#define Y_FIREBRICK_INDEX          27
#define Y_CHROMEOXIDEGREEN   upsylon::Graphic::rgb(0x66,0x80,0x14)
#define Y_CHROMEOXIDEGREEN_INDEX   28
#define Y_PERMANENT_GREEN    upsylon::Graphic::rgb(0x0a,0xc9,0x2b)
#define Y_PERMANENT_GREEN_INDEX    29
#define Y_BLUE               upsylon::Graphic::rgb(0x00,0x00,0xff)
#define Y_BLUE_INDEX               30
#define Y_GREEN              upsylon::Graphic::rgb(0x00,0xff,0x00)
#define Y_GREEN_INDEX              31
#define Y_RED                upsylon::Graphic::rgb(0xff,0x00,0x00)
#define Y_RED_INDEX                32
#define Y_RASPBERRY          upsylon::Graphic::rgb(0x87,0x26,0x57)
#define Y_RASPBERRY_INDEX          33
#define Y_CADMIUM_RED_DEEP   upsylon::Graphic::rgb(0xe3,0x17,0x0d)
#define Y_CADMIUM_RED_DEEP_INDEX   34
#define Y_VENETIAN_RED       upsylon::Graphic::rgb(0xd4,0x1a,0x1f)
#define Y_VENETIAN_RED_INDEX       35
#define Y_COBALT_GREEN       upsylon::Graphic::rgb(0x3d,0x91,0x40)
#define Y_COBALT_GREEN_INDEX       36
#define Y_CADMIUM_RED_LIGHT  upsylon::Graphic::rgb(0xff,0x03,0x0d)
#define Y_CADMIUM_RED_LIGHT_INDEX  37
#define Y_SEA_GREEN          upsylon::Graphic::rgb(0x2e,0x8b,0x57)
#define Y_SEA_GREEN_INDEX          38
#define Y_SLATE_BLUE_DARK    upsylon::Graphic::rgb(0x48,0x3d,0x8b)
#define Y_SLATE_BLUE_DARK_INDEX    39
#define Y_OLIVE_DRAB         upsylon::Graphic::rgb(0x6b,0x8e,0x23)
#define Y_OLIVE_DRAB_INDEX         40
#define Y_SIENNA             upsylon::Graphic::rgb(0xa0,0x52,0x2d)
#define Y_SIENNA_INDEX             41
#define Y_EMERALD_GREEN      upsylon::Graphic::rgb(0x00,0xc9,0x57)
#define Y_EMERALD_GREEN_INDEX      42
#define Y_BRICK              upsylon::Graphic::rgb(0x9c,0x66,0x1f)
#define Y_BRICK_INDEX              43
#define Y_GERANIUM_LAKE      upsylon::Graphic::rgb(0xe3,0x12,0x30)
#define Y_GERANIUM_LAKE_INDEX      44
#define Y_ENGLISH_RED        upsylon::Graphic::rgb(0xd4,0x3d,0x1a)
#define Y_ENGLISH_RED_INDEX        45
#define Y_BROWN_MADDER       upsylon::Graphic::rgb(0xdb,0x29,0x29)
#define Y_BROWN_MADDER_INDEX       46
#define Y_LIME_GREEN         upsylon::Graphic::rgb(0x32,0xcd,0x32)
#define Y_LIME_GREEN_INDEX         47
#define Y_DIM_GREY           upsylon::Graphic::rgb(0x69,0x69,0x69)
#define Y_DIM_GREY_INDEX           48
#define Y_RAW_SIENNA         upsylon::Graphic::rgb(0xc7,0x61,0x14)
#define Y_RAW_SIENNA_INDEX         49
#define Y_CINNABAR_GREEN     upsylon::Graphic::rgb(0x61,0xb3,0x29)
#define Y_CINNABAR_GREEN_INDEX     50
#define Y_ALIZARIN_CRIMSON   upsylon::Graphic::rgb(0xe3,0x26,0x36)
#define Y_ALIZARIN_CRIMSON_INDEX   51
#define Y_MAROON             upsylon::Graphic::rgb(0xb0,0x30,0x60)
#define Y_MAROON_INDEX             52
#define Y_COBALT             upsylon::Graphic::rgb(0x3d,0x59,0xab)
#define Y_COBALT_INDEX             53
#define Y_MADDER_LAKE_DEEP   upsylon::Graphic::rgb(0xe3,0x2e,0x30)
#define Y_MADDER_LAKE_DEEP_INDEX   54
#define Y_ORANGE_RED         upsylon::Graphic::rgb(0xff,0x45,0x00)
#define Y_ORANGE_RED_INDEX         55
#define Y_PERMANENT_VIOLET   upsylon::Graphic::rgb(0xdb,0x26,0x45)
#define Y_PERMANENT_VIOLET_INDEX   56
#define Y_GOLDENROD_DARK     upsylon::Graphic::rgb(0xb8,0x86,0x0b)
#define Y_GOLDENROD_DARK_INDEX     57
#define Y_GREENISH_UMBER     upsylon::Graphic::rgb(0xff,0x3d,0x0d)
#define Y_GREENISH_UMBER_INDEX     58
#define Y_MANGANESE_BLUE     upsylon::Graphic::rgb(0x03,0xa8,0x9e)
#define Y_MANGANESE_BLUE_INDEX     59
#define Y_COBALT_VIOLETDEEP  upsylon::Graphic::rgb(0x91,0x21,0x9e)
#define Y_COBALT_VIOLETDEEP_INDEX  60
#define Y_ROSE_MADDER        upsylon::Graphic::rgb(0xe3,0x36,0x38)
#define Y_ROSE_MADDER_INDEX        61
#define Y_TURQUOISE_BLUE     upsylon::Graphic::rgb(0x00,0xc7,0x8c)
#define Y_TURQUOISE_BLUE_INDEX     62
#define Y_CHOCOLATE          upsylon::Graphic::rgb(0xd2,0x69,0x1e)
#define Y_CHOCOLATE_INDEX          63
#define Y_SEA_GREEN_MEDIUM   upsylon::Graphic::rgb(0x3c,0xb3,0x71)
#define Y_SEA_GREEN_MEDIUM_INDEX   64
#define Y_VIOLET_REDMEDIUM   upsylon::Graphic::rgb(0xc7,0x15,0x85)
#define Y_VIOLET_REDMEDIUM_INDEX   65
#define Y_CADMIUM_ORANGE     upsylon::Graphic::rgb(0xff,0x61,0x03)
#define Y_CADMIUM_ORANGE_INDEX     66
#define Y_GOLD_OCHRE         upsylon::Graphic::rgb(0xc7,0x78,0x26)
#define Y_GOLD_OCHRE_INDEX         67
#define Y_VIOLET_DARK        upsylon::Graphic::rgb(0x94,0x00,0xd3)
#define Y_VIOLET_DARK_INDEX        68
#define Y_WARM_GREY          upsylon::Graphic::rgb(0x80,0x80,0x69)
#define Y_WARM_GREY_INDEX          69
#define Y_MARS_YELLOW        upsylon::Graphic::rgb(0xe3,0x70,0x1a)
#define Y_MARS_YELLOW_INDEX        70
#define Y_FLESH_OCHRE        upsylon::Graphic::rgb(0xff,0x57,0x21)
#define Y_FLESH_OCHRE_INDEX        71
#define Y_LAWN_GREEN         upsylon::Graphic::rgb(0x7c,0xfc,0x00)
#define Y_LAWN_GREEN_INDEX         72
#define Y_SEA_GREEN_LIGHT    upsylon::Graphic::rgb(0x20,0xb2,0xaa)
#define Y_SEA_GREEN_LIGHT_INDEX    73
#define Y_STEEL_BLUE         upsylon::Graphic::rgb(0x46,0x82,0xb4)
#define Y_STEEL_BLUE_INDEX         74
#define Y_YELLOW_OCHRE       upsylon::Graphic::rgb(0xe3,0x82,0x17)
#define Y_YELLOW_OCHRE_INDEX       75
#define Y_CHARTREUSE         upsylon::Graphic::rgb(0x7f,0xff,0x00)
#define Y_CHARTREUSE_INDEX         76
#define Y_SPRING_GREEN       upsylon::Graphic::rgb(0x00,0xff,0x7f)
#define Y_SPRING_GREEN_INDEX       77
#define Y_ORANGE             upsylon::Graphic::rgb(0xff,0x80,0x00)
#define Y_ORANGE_INDEX             78
#define Y_SLATE_GREY         upsylon::Graphic::rgb(0x70,0x80,0x90)
#define Y_SLATE_GREY_INDEX         79
#define Y_VIOLET_RED         upsylon::Graphic::rgb(0xd0,0x20,0x90)
#define Y_VIOLET_RED_INDEX         80
#define Y_VIOLET             upsylon::Graphic::rgb(0x8f,0x5e,0x99)
#define Y_VIOLET_INDEX             81
#define Y_CERULEAN           upsylon::Graphic::rgb(0x05,0xb8,0xcc)
#define Y_CERULEAN_INDEX           82
#define Y_DARK_ORANGE        upsylon::Graphic::rgb(0xff,0x8c,0x00)
#define Y_DARK_ORANGE_INDEX        83
#define Y_ROYAL_BLUE         upsylon::Graphic::rgb(0x41,0x69,0xe1)
#define Y_ROYAL_BLUE_INDEX         84
#define Y_COLD_GREY          upsylon::Graphic::rgb(0x80,0x8a,0x87)
#define Y_COLD_GREY_INDEX          85
#define Y_PERU               upsylon::Graphic::rgb(0xcd,0x85,0x3f)
#define Y_PERU_INDEX               86
#define Y_SLATE_BLUE         upsylon::Graphic::rgb(0x6a,0x5a,0xcd)
#define Y_SLATE_BLUE_INDEX         87
#define Y_SPRING_GREENMEDIUM upsylon::Graphic::rgb(0x00,0xfa,0x9a)
#define Y_SPRING_GREENMEDIUM_INDEX 88
#define Y_BLUE_VIOLET        upsylon::Graphic::rgb(0x8a,0x2b,0xe2)
#define Y_BLUE_VIOLET_INDEX        89
#define Y_ORCHID_DARK        upsylon::Graphic::rgb(0x99,0x32,0xcc)
#define Y_ORCHID_DARK_INDEX        90
#define Y_SLATE_GREY_LIGHT   upsylon::Graphic::rgb(0x77,0x88,0x99)
#define Y_SLATE_GREY_LIGHT_INDEX   91
#define Y_YELLOW_GREEN       upsylon::Graphic::rgb(0x9a,0xcd,0x32)
#define Y_YELLOW_GREEN_INDEX       92
#define Y_CADET              upsylon::Graphic::rgb(0x5f,0x9e,0xa0)
#define Y_CADET_INDEX              93
#define Y_PEACOCK            upsylon::Graphic::rgb(0x33,0xa1,0xc9)
#define Y_PEACOCK_INDEX            94
#define Y_CARROT             upsylon::Graphic::rgb(0xed,0x91,0x21)
#define Y_CARROT_INDEX             95
#define Y_GOLDENROD          upsylon::Graphic::rgb(0xda,0xa5,0x20)
#define Y_GOLDENROD_INDEX          96
#define Y_TURQUOISE_DARK     upsylon::Graphic::rgb(0x00,0xce,0xd1)
#define Y_TURQUOISE_DARK_INDEX     97
#define Y_DEEP_PINK          upsylon::Graphic::rgb(0xff,0x14,0x93)
#define Y_DEEP_PINK_INDEX          98
#define Y_TOMATO             upsylon::Graphic::rgb(0xff,0x63,0x47)
#define Y_TOMATO_INDEX             99
#define Y_CADMIUM_YELLOW     upsylon::Graphic::rgb(0xff,0x99,0x12)
#define Y_CADMIUM_YELLOW_INDEX     100
#define Y_DODGER_BLUE        upsylon::Graphic::rgb(0x1e,0x90,0xff)
#define Y_DODGER_BLUE_INDEX        101
#define Y_PURPLE             upsylon::Graphic::rgb(0xa0,0x20,0xf0)
#define Y_PURPLE_INDEX             102
#define Y_BEIGE              upsylon::Graphic::rgb(0xa3,0x94,0x80)
#define Y_BEIGE_INDEX              103
#define Y_NAPLESYELLOWDEEP   upsylon::Graphic::rgb(0xff,0xa8,0x12)
#define Y_NAPLESYELLOWDEEP_INDEX   104
#define Y_FLESH              upsylon::Graphic::rgb(0xff,0x7d,0x40)
#define Y_FLESH_INDEX              105
#define Y_SKY_BLUE_DEEP      upsylon::Graphic::rgb(0x00,0xbf,0xff)
#define Y_SKY_BLUE_DEEP_INDEX      106
#define Y_AUREOLINE_YELLOW   upsylon::Graphic::rgb(0xff,0xa8,0x24)
#define Y_AUREOLINE_YELLOW_INDEX   107
#define Y_CORAL              upsylon::Graphic::rgb(0xff,0x7f,0x50)
#define Y_CORAL_INDEX              108
#define Y_SLATE_BLUE_MEDIUM  upsylon::Graphic::rgb(0x7b,0x68,0xee)
#define Y_SLATE_BLUE_MEDIUM_INDEX  109
#define Y_GOLD               upsylon::Graphic::rgb(0xff,0xd7,0x00)
#define Y_GOLD_INDEX               110
#define Y_ROSY_BROWN         upsylon::Graphic::rgb(0xbc,0x8f,0x8f)
#define Y_ROSY_BROWN_INDEX         111
#define Y_SEA_GREEN_DARK     upsylon::Graphic::rgb(0x8f,0xbc,0x8f)
#define Y_SEA_GREEN_DARK_INDEX     112
#define Y_GREEN_YELLOW       upsylon::Graphic::rgb(0xad,0xff,0x2f)
#define Y_GREEN_YELLOW_INDEX       113
#define Y_AQUAMARINEMEDIUM   upsylon::Graphic::rgb(0x66,0xcd,0xaa)
#define Y_AQUAMARINEMEDIUM_INDEX   114
#define Y_VIRIDIAN_LIGHT     upsylon::Graphic::rgb(0x6e,0xff,0x70)
#define Y_VIRIDIAN_LIGHT_INDEX     115
#define Y_PURPLE_MEDIUM      upsylon::Graphic::rgb(0x93,0x70,0xdb)
#define Y_PURPLE_MEDIUM_INDEX      116
#define Y_VIOLET_RED_PALE    upsylon::Graphic::rgb(0xdb,0x70,0x93)
#define Y_VIOLET_RED_PALE_INDEX    117
#define Y_KHAKI_DARK         upsylon::Graphic::rgb(0xbd,0xb7,0x6b)
#define Y_KHAKI_DARK_INDEX         118
#define Y_ORCHID_MEDIUM      upsylon::Graphic::rgb(0xba,0x55,0xd3)
#define Y_ORCHID_MEDIUM_INDEX      119
#define Y_CADMIUM_LEMON      upsylon::Graphic::rgb(0xff,0xe3,0x03)
#define Y_CADMIUM_LEMON_INDEX      120
#define Y_TURQUOISE_MEDIUM   upsylon::Graphic::rgb(0x48,0xd1,0xcc)
#define Y_TURQUOISE_MEDIUM_INDEX   121
#define Y_CORNFLOWER         upsylon::Graphic::rgb(0x64,0x95,0xed)
#define Y_CORNFLOWER_INDEX         122
#define Y_SALMON             upsylon::Graphic::rgb(0xfa,0x80,0x72)
#define Y_SALMON_INDEX             123
#define Y_CORAL_LIGHT        upsylon::Graphic::rgb(0xf0,0x80,0x80)
#define Y_CORAL_LIGHT_INDEX        124
#define Y_TURQUOISE          upsylon::Graphic::rgb(0x40,0xe0,0xd0)
#define Y_TURQUOISE_INDEX          125
#define Y_SLATE_BLUE_LIGHT   upsylon::Graphic::rgb(0x84,0x70,0xff)
#define Y_SLATE_BLUE_LIGHT_INDEX   126
#define Y_MELON              upsylon::Graphic::rgb(0xe3,0xa8,0x69)
#define Y_MELON_INDEX              127
#define Y_SANDY_BROWN        upsylon::Graphic::rgb(0xf4,0xa4,0x60)
#define Y_SANDY_BROWN_INDEX        128
#define Y_CYAN               upsylon::Graphic::rgb(0x00,0xff,0xff)
#define Y_CYAN_INDEX               129
#define Y_MAGENTA            upsylon::Graphic::rgb(0xff,0x00,0xff)
#define Y_MAGENTA_INDEX            130
#define Y_YELLOW             upsylon::Graphic::rgb(0xff,0xff,0x00)
#define Y_YELLOW_INDEX             131
#define Y_BANANA             upsylon::Graphic::rgb(0xe3,0xcf,0x57)
#define Y_BANANA_INDEX             132
#define Y_TAN                upsylon::Graphic::rgb(0xd2,0xb4,0x8c)
#define Y_TAN_INDEX                133
#define Y_LIGHT_SALMON       upsylon::Graphic::rgb(0xff,0xa0,0x7a)
#define Y_LIGHT_SALMON_INDEX       134
#define Y_HOT_PINK           upsylon::Graphic::rgb(0xff,0x69,0xb4)
#define Y_HOT_PINK_INDEX           135
#define Y_BURLYWOOD          upsylon::Graphic::rgb(0xde,0xb8,0x87)
#define Y_BURLYWOOD_INDEX          136
#define Y_ORCHID             upsylon::Graphic::rgb(0xda,0x70,0xd6)
#define Y_ORCHID_INDEX             137
#define Y_GREEN_PALE         upsylon::Graphic::rgb(0x98,0xfb,0x98)
#define Y_GREEN_PALE_INDEX         138
#define Y_GREY               upsylon::Graphic::rgb(0xc0,0xc0,0xc0)
#define Y_GREY_INDEX               139
#define Y_SKY_BLUE           upsylon::Graphic::rgb(0x87,0xce,0xeb)
#define Y_SKY_BLUE_INDEX           140
#define Y_LIGHT_GOLDENROD    upsylon::Graphic::rgb(0xee,0xdd,0x82)
#define Y_LIGHT_GOLDENROD_INDEX    141
#define Y_SKY_BLUE_LIGHT     upsylon::Graphic::rgb(0x87,0xce,0xfa)
#define Y_SKY_BLUE_LIGHT_INDEX     142
#define Y_AQUAMARINE         upsylon::Graphic::rgb(0x7f,0xff,0xd4)
#define Y_AQUAMARINE_INDEX         143
#define Y_STEEL_BLUE_LIGHT   upsylon::Graphic::rgb(0xb0,0xc4,0xde)
#define Y_STEEL_BLUE_LIGHT_INDEX   144
#define Y_PLUM               upsylon::Graphic::rgb(0xdd,0xa0,0xdd)
#define Y_PLUM_INDEX               145
#define Y_KHAKI              upsylon::Graphic::rgb(0xf0,0xe6,0x8c)
#define Y_KHAKI_INDEX              146
#define Y_BLUE_LIGHT         upsylon::Graphic::rgb(0xad,0xd8,0xe6)
#define Y_BLUE_LIGHT_INDEX         147
#define Y_THISTLE            upsylon::Graphic::rgb(0xd8,0xbf,0xd8)
#define Y_THISTLE_INDEX            148
#define Y_PINK_LIGHT         upsylon::Graphic::rgb(0xff,0xb6,0xc1)
#define Y_PINK_LIGHT_INDEX         149
#define Y_POWDER_BLUE        upsylon::Graphic::rgb(0xb0,0xe0,0xe6)
#define Y_POWDER_BLUE_INDEX        150
#define Y_LIGHT_GREY         upsylon::Graphic::rgb(0xd3,0xd3,0xd3)
#define Y_LIGHT_GREY_INDEX         151
#define Y_GOLDENROD_PALE     upsylon::Graphic::rgb(0xee,0xe8,0xaa)
#define Y_GOLDENROD_PALE_INDEX     152
#define Y_MINT               upsylon::Graphic::rgb(0xbd,0xfc,0xc9)
#define Y_MINT_INDEX               153
#define Y_WHEAT              upsylon::Graphic::rgb(0xf5,0xde,0xb3)
#define Y_WHEAT_INDEX              154
#define Y_NAVAJO_WHITE       upsylon::Graphic::rgb(0xff,0xde,0xad)
#define Y_NAVAJO_WHITE_INDEX       155
#define Y_PINK               upsylon::Graphic::rgb(0xff,0xc0,0xcb)
#define Y_PINK_INDEX               156
#define Y_TURQUOISE_PALE     upsylon::Graphic::rgb(0xaf,0xee,0xee)
#define Y_TURQUOISE_PALE_INDEX     157
#define Y_PEACH_PUFF         upsylon::Graphic::rgb(0xff,0xda,0xb9)
#define Y_PEACH_PUFF_INDEX         158
#define Y_GAINSBORO          upsylon::Graphic::rgb(0xdc,0xdc,0xdc)
#define Y_GAINSBORO_INDEX          159
#define Y_MOCCASIN           upsylon::Graphic::rgb(0xff,0xe4,0xb5)
#define Y_MOCCASIN_INDEX           160
#define Y_BISQUE             upsylon::Graphic::rgb(0xff,0xe4,0xc4)
#define Y_BISQUE_INDEX             161
#define Y_EGGSHELL           upsylon::Graphic::rgb(0xfc,0xe6,0xc9)
#define Y_EGGSHELL_INDEX           162
#define Y_BLANCHED_ALMOND    upsylon::Graphic::rgb(0xff,0xeb,0xcd)
#define Y_BLANCHED_ALMOND_INDEX    163
#define Y_ANTIQUE_WHITE      upsylon::Graphic::rgb(0xfa,0xeb,0xd7)
#define Y_ANTIQUE_WHITE_INDEX      164
#define Y_PAPAYA_WHIP        upsylon::Graphic::rgb(0xff,0xef,0xd5)
#define Y_PAPAYA_WHIP_INDEX        165
#define Y_MISTY_ROSE         upsylon::Graphic::rgb(0xff,0xe4,0xe1)
#define Y_MISTY_ROSE_INDEX         166
#define Y_GOLDENROD_LIGHT    upsylon::Graphic::rgb(0xfa,0xfa,0xd2)
#define Y_GOLDENROD_LIGHT_INDEX    167
#define Y_LAVENDER           upsylon::Graphic::rgb(0xe6,0xe6,0xfa)
#define Y_LAVENDER_INDEX           168
#define Y_LEMON_CHIFFON      upsylon::Graphic::rgb(0xff,0xfa,0xcd)
#define Y_LEMON_CHIFFON_INDEX      169
#define Y_LIGHT_BEIGE        upsylon::Graphic::rgb(0xf5,0xf5,0xdc)
#define Y_LIGHT_BEIGE_INDEX        170
#define Y_LINEN              upsylon::Graphic::rgb(0xfa,0xf0,0xe6)
#define Y_LINEN_INDEX              171
#define Y_CORNSILK           upsylon::Graphic::rgb(0xff,0xf8,0xdc)
#define Y_CORNSILK_INDEX           172
#define Y_OLD_LACE           upsylon::Graphic::rgb(0xfd,0xf5,0xe6)
#define Y_OLD_LACE_INDEX           173
#define Y_CYAN_WHITE         upsylon::Graphic::rgb(0xe0,0xff,0xff)
#define Y_CYAN_WHITE_INDEX         174
#define Y_YELLOW_LIGHT       upsylon::Graphic::rgb(0xff,0xff,0xe0)
#define Y_YELLOW_LIGHT_INDEX       175
#define Y_HONEYDEW           upsylon::Graphic::rgb(0xf0,0xff,0xf0)
#define Y_HONEYDEW_INDEX           176
#define Y_WHITE_SMOKE        upsylon::Graphic::rgb(0xf5,0xf5,0xf5)
#define Y_WHITE_SMOKE_INDEX        177
#define Y_SEASHELL           upsylon::Graphic::rgb(0xff,0xf5,0xee)
#define Y_SEASHELL_INDEX           178
#define Y_LAVENDER_BLUSH     upsylon::Graphic::rgb(0xff,0xf0,0xf5)
#define Y_LAVENDER_BLUSH_INDEX     179
#define Y_ALICE_BLUE         upsylon::Graphic::rgb(0xf0,0xf8,0xff)
#define Y_ALICE_BLUE_INDEX         180
#define Y_FLORAL_WHITE       upsylon::Graphic::rgb(0xff,0xfa,0xf0)
#define Y_FLORAL_WHITE_INDEX       181
#define Y_TITANIUM_WHITE     upsylon::Graphic::rgb(0xfc,0xff,0xf0)
#define Y_TITANIUM_WHITE_INDEX     182
#define Y_AZURE              upsylon::Graphic::rgb(0xf0,0xff,0xff)
#define Y_AZURE_INDEX              183
#define Y_IVORY              upsylon::Graphic::rgb(0xff,0xff,0xf0)
#define Y_IVORY_INDEX              184
#define Y_MINT_CREAM         upsylon::Graphic::rgb(0xf5,0xff,0xfa)
#define Y_MINT_CREAM_INDEX         185
#define Y_GHOST_WHITE        upsylon::Graphic::rgb(0xf8,0xf8,0xff)
#define Y_GHOST_WHITE_INDEX        186
#define Y_SNOW               upsylon::Graphic::rgb(0xff,0xfa,0xfa)
#define Y_SNOW_INDEX               187
#define Y_ZINC_WHITE         upsylon::Graphic::rgb(0xfd,0xf8,0xff)
#define Y_ZINC_WHITE_INDEX         188
#define Y_WHITE              upsylon::Graphic::rgb(0xff,0xff,0xff)
#define Y_WHITE_INDEX              189
