FIND_PACKAGE(MPI)

IF(MPI_FOUND)
  #avoid some problem with whitespaces
  CMAKE_POLICY(SET CMP0004 OLD)

  INCLUDE_DIRECTORIES(${MPI_INCLUDE_PATH})

	#compatibility layer with MS MPI
  IF(Y_WINDOWS AND Y_GNU)
    ADD_DEFINITIONS( -DMSMPI_NO_SAL=1 )
  ENDIF()
	
  MESSAGE(STATUS "MPIEXEC_EXECUTABLE   = <${MPIEXEC_EXECUTABLE}>")
  MESSAGE(STATUS "MPIEXEC_NUMPROC_FLAG = <${MPIEXEC_NUMPROC_FLAG}>")
  MESSAGE(STATUS "MPIEXEC_MAX_NUMPROCS = <${MPIEXEC_MAX_NUMPROCS}>")
  MESSAGE(STATUS "MPIEXEC_PREFLAGS     = <${MPIEXEC_PREFLAGS}>")
  MESSAGE(STATUS "MPIEXEC_POSTFLAGS    = <${MPIEXEC_POSTFLAGS}>")
  
  MACRO(Y_MPI THE_NAME THE_EXECUTABLE)
  ADD_TEST(NAME ${THE_NAME} COMMAND ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${MPIEXEC_MAX_NUMPROCS} ${THE_EXECUTABLE} ${ARGN} )
  ENDMACRO()
  
ENDIF()
