FIND_PROGRAM(MAKE make)
FILE( GLOB_RECURSE Makefiles "src/*/makefile")

FOREACH(f IN LISTS Makefiles )

#MESSAGE(${f})
GET_FILENAME_COMPONENT(d ${f} DIRECTORY)
MESSAGE( STATUS "Cleaning ${d}" )
EXECUTE_PROCESS(COMMAND ${MAKE} -s -C ${d} clean)

ENDFOREACH(f)
