all:

%.pdf:%.tex
	pdflatex $< && pdflatex $<

clean:
	rm -f *.aux *.log *.synctex.gz lsf.pdf
	rm -f gls.pdf
	rm -f newt.pdf
	rm -f protodiff.pdf
	rm -f spline.pdf
	rm -f zero.pdf
	rm -f splines.pdf
	rm -f zircon.pdf
	rm -f diffusion.pdf
	rm -f fvm.pdf
	rm -f formula.pdf
